apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccountName }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      containers:
      - name: streamlit
        image: "{{ .Values.streamlit.image.repository }}:{{ .Values.streamlit.image.tag }}"
        imagePullPolicy: {{ .Values.streamlit.image.pullPolicy }}
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: "{{ .Values.streamlit.env.API_URL }}"
        resources:
          {{- toYaml .Values.streamlit.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 5