apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  labels:
    app: streamlit
spec:
  selector:
    app: streamlit
  ports:
  - protocol: TCP
    port: {{ .Values.streamlit.service.port }}
    targetPort: 8501
  type: {{ .Values.streamlit.service.type }}