services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    networks:
      - ml-network

  streamlit:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://fastapi:8000
    depends_on:
      - fastapi
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge