apiVersion: v1
kind: Secret
metadata:
  name: house-price-predictor-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Venkat8538/house-price-predictor