FROM apache/airflow:2.7.0

USER root
RUN apt-get update && apt-get install -y git

USER airflow
RUN pip install --no-cache-dir \
    scikit-learn==1.3.2 \
    pandas==2.0.3 \
    numpy==1.24.4 \
    xgboost==2.1.4 \
    joblib==1.4.2 \
    pyyaml==6.0.1 \
    mlflow==2.8.0