model:
  best_model: GradientBoosting
  feature_sets:
    rfe:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '9'
    - '10'
    - '13'
    - '14'
  mae: 11244.395105733129
  name: house_price_model_v2
  parameters:
    alpha: 0.9
    ccp_alpha: 0.0
    criterion: friedman_mse
    init: null
    learning_rate: 0.05
    loss: squared_error
    max_depth: 5
    max_features: null
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    min_samples_leaf: 2
    min_samples_split: 5
    min_weight_fraction_leaf: 0.0
    n_estimators: 200
    n_iter_no_change: null
    random_state: 42
    subsample: 0.9
    tol: 0.0001
    validation_fraction: 0.1
    verbose: 0
    warm_start: false
  r2_score: 0.9938643801545451
  target_variable: price
