name: Build and Deploy Web Apps

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/api/**'
      - 'streamlit_app/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - 'helm/**'

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: house-price-mlops

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::027419661856:role/GitHubActionsRole
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build and push FastAPI image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:fastapi-$IMAGE_TAG .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:fastapi .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:fastapi-$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:fastapi

    - name: Build and push Streamlit image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:streamlit-$IMAGE_TAG ./streamlit_app
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:streamlit ./streamlit_app
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:streamlit-$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:streamlit
    
    - name: Update Helm values
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Update repository URLs
        sed -i "s|repository: .*|repository: $ECR_REGISTRY/$ECR_REPOSITORY|g" helm/mlops-app/values.yaml
        
        # Update image tags - FastAPI first occurrence
        sed -i "0,/tag: .*/s//tag: fastapi-$IMAGE_TAG/" helm/mlops-app/values.yaml
        
        # Update image tags - Streamlit second occurrence  
        sed -i "0,/tag: fastapi-$IMAGE_TAG/!s/tag: .*/tag: streamlit-$IMAGE_TAG/" helm/mlops-app/values.yaml
    
    - name: Commit updated Helm values
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add helm/
        git diff --staged --quiet || git commit -m "Update Helm image tags to ${{ github.sha }}"
        git push