name: ML Pipeline CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'src/models/**'
      - 'src/features/**'
      - 'src/data/**'
      - 'configs/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/models/**'
      - 'src/features/**'
      - 'src/data/**'
      - 'configs/**'

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run tests
      run: |
        # Add your tests here
        echo "Running ML model tests..."
        # pytest tests/ --verbose
    
    - name: Build Docker images
      run: |
        docker build -t house-price-fastapi .
        docker build -t house-price-streamlit ./streamlit_app
    
    - name: Deploy containers
      run: |
        echo "Deploying updated containers..."
        # In production, this would deploy to your cloud provider
    
    - name: Trigger Airflow ML Pipeline
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Triggering Airflow ML pipeline for model retraining..."
        curl -X POST \
          "${{ secrets.AIRFLOW_URL }}/api/v1/dags/house_price_ml_pipeline/dagRuns" \
          -H "Content-Type: application/json" \
          -H "Authorization: Basic ${{ secrets.AIRFLOW_AUTH }}" \
          -d '{
            "conf": {
              "triggered_by": "github_actions",
              "commit_sha": "${{ github.sha }}",
              "branch": "${{ github.ref_name }}"
            }
          }'
    
    - name: Notify on success
      if: success()
      run: |
        echo "✅ ML Pipeline triggered successfully!"
        echo "Check Airflow UI for pipeline status: ${{ secrets.AIRFLOW_URL }}"
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Pipeline failed. Check logs for details."