name: Model Training with Versioning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::027419661856:role/GitHubActionsRole
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Trigger SageMaker Pipeline
      run: |
        echo "🚀 Triggering SageMaker ML Pipeline..."
        EXECUTION_ARN=$(aws sagemaker start-pipeline-execution \
          --pipeline-name house-price-pipeline \
          --region ${{ env.AWS_REGION }} \
          --query 'PipelineExecutionArn' --output text)
        
        echo "✅ Pipeline started: $EXECUTION_ARN"
        echo "📊 Monitor at: https://console.aws.amazon.com/sagemaker/home?region=${{ env.AWS_REGION }}#/pipelines"