name: Model Promotion

on:
  workflow_dispatch:
    inputs:
      model_version:
        description: 'Model version to promote'
        required: true
        type: string
      stage:
        description: 'Target stage'
        required: true
        type: choice
        options:
          - Staging
          - Production
        default: 'Staging'

env:
  PYTHON_VERSION: '3.11'

jobs:
  promote-model:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow
    
    - name: Promote model
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: |
        python -c "
        import mlflow
        from mlflow.tracking import MlflowClient
        import os
        
        # Set MLflow tracking URI
        mlflow.set_tracking_uri(os.getenv('MLFLOW_TRACKING_URI', 'http://localhost:5000'))
        client = MlflowClient()
        
        model_name = 'house-price-predictor'
        version = '${{ github.event.inputs.model_version }}'
        stage = '${{ github.event.inputs.stage }}'
        
        # Promote model to target stage
        client.transition_model_version_stage(
            name=model_name,
            version=version,
            stage=stage,
            archive_existing_versions=True
        )
        
        print(f'✅ Model {model_name} version {version} promoted to {stage}')
        "
    
    - name: Update deployment config
      if: github.event.inputs.stage == 'Production'
      run: |
        echo "MODEL_VERSION=${{ github.event.inputs.model_version }}" > .env.production
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .env.production
        git commit -m "Update production model version to ${{ github.event.inputs.model_version }}"
        git push